import type { OrgMatrix, Person } from "./types";

const palette = {
  sonance: "#1d4ed8",
  iport: "#0f766e",
  james: "#ea580c",
  blaze: "#b91c1c",
  residential: "#7c3aed",
  professional: "#2563eb",
  product: "#0891b2",
  marketing: "#9333ea",
  sales: "#f97316",
  hr: "#2563eb",
  finance: "#0f172a",
  executive: "#111827",
};

export const orgMatrix: OrgMatrix = {
  brands: [
    {
      id: "sonance",
      label: "Sonance",
      description: "Flagship architectural audio solutions and core brand.",
      color: palette.sonance,
    },
    {
      id: "iport",
      label: "iPort",
      description: "Integrated control solutions bridging mobile and home systems.",
      color: palette.iport,
    },
    {
      id: "james",
      label: "James Cloud Speaker",
      description: "Ultra-custom cloud speaker experiences for luxury installations.",
      color: palette.james,
    },
    {
      id: "blaze",
      label: "Blaze Audio",
      description: "High-output performance audio for demanding professional venues.",
      color: palette.blaze,
    },
  ],
  channels: [
    {
      id: "residential-retail",
      label: "Residential Retail",
      description: "Dealers and storefronts driving Sonance brand awareness.",
      color: palette.residential,
    },
    {
      id: "residential-mid",
      label: "Residential Mid-Market",
      description: "Regional integrators focused on scalable residential projects.",
      color: palette.residential,
    },
    {
      id: "residential-luxury",
      label: "Residential Luxury",
      description: "Design-first bespoke installations for flagship properties.",
      color: palette.residential,
    },
    {
      id: "professional-enterprise",
      label: "Professional Enterprise",
      description: "Enterprise deployments including corporate campuses and retail chains.",
      color: palette.professional,
    },
    {
      id: "professional-audio",
      label: "Professional Audio",
      description: "Large-scale performance and hospitality venues.",
      color: palette.professional,
    },
  ],
  departments: [
    {
      id: "executive",
      label: "Executive Leadership",
      description: "Sets strategic direction, ensures alignment across brands and channels, and provides corporate governance. Leaders in this department span multiple brands and channels, enabling cross-functional collaboration and matrixed decision-making.",
      color: palette.executive,
    },
    {
      id: "product",
      label: "Product Development",
      description: "Owns product strategy, roadmap planning, industrial design, and integration architecture across all brands. Works closely with brand GMs and channel leaders to ensure products meet market needs while maintaining cohesive development practices.",
      color: palette.product,
    },
    {
      id: "marketing",
      label: "Marketing",
      description: "Develops brand storytelling, demand generation programs, and channel marketing initiatives. Coordinates integrated marketing strategies across brands while enabling brand-specific positioning and messaging for residential and professional markets.",
      color: palette.marketing,
    },
    {
      id: "sales",
      label: "Sales",
      description: "Manages channel partnerships, key accounts, and revenue operations across residential and professional segments. Coordinates sales strategies for multiple brands while building deep relationships with dealers, integrators, and enterprise customers.",
      color: palette.sales,
    },
    {
      id: "hr",
      label: "People & Culture",
      description: "Leads talent acquisition, organizational development, and culture initiatives. Supports matrixed leadership development, enables cross-functional collaboration, and ensures the organization has the capabilities to succeed in a complex matrix structure.",
      color: palette.hr,
    },
    {
      id: "finance",
      label: "Finance",
      description: "Provides financial planning, forecasting, and performance analytics across all brands and channels. Ensures fiscal discipline while enabling strategic investments. Supports brand GMs and channel leaders with financial insights and guidance.",
      color: palette.finance,
    },
  ],
  leadership: [
    {
      id: "person-alex-morgan",
      name: "Alex Morgan",
      title: "Chief Executive Officer",
      avatarInitials: "AM",
      brandIds: ["sonance", "iport", "james", "blaze"],
      channelIds: [
        "residential-retail",
        "residential-mid",
        "residential-luxury",
        "professional-enterprise",
        "professional-audio",
      ],
      departmentIds: ["executive"],
    },
    {
      id: "person-jules-meyer",
      name: "Jules Meyer",
      title: "Chief Financial Officer",
      avatarInitials: "JM",
      brandIds: ["sonance", "blaze"],
      channelIds: ["professional-enterprise", "professional-audio"],
      departmentIds: ["executive", "finance"],
      reportsToId: "person-alex-morgan",
    },
    {
      id: "person-ethan-rios",
      name: "Ethan Rios",
      title: "General Manager, Sonance",
      avatarInitials: "ER",
      brandIds: ["sonance"],
      primaryBrandId: "sonance",
      channelIds: ["residential-retail", "residential-mid", "professional-enterprise"],
      departmentIds: ["product", "sales"],
      reportsToId: "person-alex-morgan",
    },
    {
      id: "person-amelia-park",
      name: "Amelia Park",
      title: "General Manager, iPort",
      avatarInitials: "AP",
      brandIds: ["iport"],
      primaryBrandId: "iport",
      channelIds: ["residential-mid", "professional-enterprise"],
      departmentIds: ["product", "marketing"],
      reportsToId: "person-alex-morgan",
    },
    {
      id: "person-zoe-harper",
      name: "Zoe Harper",
      title: "General Manager, James Cloud Speaker",
      avatarInitials: "ZH",
      brandIds: ["james"],
      primaryBrandId: "james",
      channelIds: ["residential-luxury"],
      departmentIds: ["product", "marketing"],
      reportsToId: "person-alex-morgan",
    },
    {
      id: "person-liam-dorsey",
      name: "Liam Dorsey",
      title: "General Manager, Blaze Audio",
      avatarInitials: "LD",
      brandIds: ["blaze"],
      primaryBrandId: "blaze",
      channelIds: ["professional-audio", "professional-enterprise"],
      departmentIds: ["sales", "product"],
      reportsToId: "person-alex-morgan",
    },
    {
      id: "person-sophia-ng",
      name: "Sophia Ng",
      title: "Chief Product Officer",
      avatarInitials: "SN",
      brandIds: ["sonance", "james", "iport"],
      channelIds: ["residential-luxury", "residential-mid", "professional-audio"],
      departmentIds: ["executive", "product"],
      reportsToId: "person-alex-morgan",
    },
    {
      id: "person-daniel-kim",
      name: "Daniel Kim",
      title: "VP, Integrated Marketing",
      avatarInitials: "DK",
      brandIds: ["sonance", "iport", "blaze"],
      channelIds: ["residential-retail", "professional-enterprise"],
      departmentIds: ["marketing"],
      reportsToId: "person-alex-morgan",
    },
    {
      id: "person-lena-ortiz",
      name: "Lena Ortiz",
      title: "VP, Residential Channel",
      avatarInitials: "LO",
      brandIds: ["sonance", "iport", "james"],
      channelIds: ["residential-retail", "residential-mid", "residential-luxury"],
      departmentIds: ["sales"],
      reportsToId: "person-alex-morgan",
    },
    {
      id: "person-omar-hassan",
      name: "Omar Hassan",
      title: "VP, Professional Channel",
      avatarInitials: "OH",
      brandIds: ["blaze", "sonance"],
      channelIds: ["professional-enterprise", "professional-audio"],
      departmentIds: ["sales"],
      reportsToId: "person-alex-morgan",
    },
    {
      id: "person-natalie-wade",
      name: "Natalie Wade",
      title: "Head of People & Culture",
      avatarInitials: "NW",
      brandIds: ["sonance", "iport", "james", "blaze"],
      channelIds: ["residential-mid", "professional-enterprise"],
      departmentIds: ["hr"],
      reportsToId: "person-alex-morgan",
    },
    {
      id: "person-ava-cho",
      name: "Ava Cho",
      title: "Director, Experience Design",
      avatarInitials: "AC",
      brandIds: ["james", "sonance"],
      channelIds: ["residential-luxury", "professional-audio"],
      departmentIds: ["product", "marketing"],
      reportsToId: "person-sophia-ng",
    },
    {
      id: "person-victor-sloan",
      name: "Victor Sloan",
      title: "Director, Enterprise Programs",
      avatarInitials: "VS",
      brandIds: ["sonance", "blaze"],
      channelIds: ["professional-enterprise"],
      departmentIds: ["sales"],
      reportsToId: "person-omar-hassan",
    },
    {
      id: "person-harper-ellis",
      name: "Harper Ellis",
      title: "Director, Luxury Partnerships",
      avatarInitials: "HE",
      brandIds: ["james", "sonance"],
      channelIds: ["residential-luxury"],
      departmentIds: ["sales", "marketing"],
      reportsToId: "person-lena-ortiz",
    },
    {
      id: "person-ryan-tate",
      name: "Ryan Tate",
      title: "Director, Retail Programs",
      avatarInitials: "RT",
      brandIds: ["sonance", "iport"],
      channelIds: ["residential-retail", "residential-mid"],
      departmentIds: ["sales", "marketing"],
      reportsToId: "person-lena-ortiz",
    },
    {
      id: "person-joelle-carter",
      name: "Joelle Carter",
      title: "Director, Integrated Systems",
      avatarInitials: "JC",
      brandIds: ["iport", "sonance"],
      channelIds: ["residential-mid", "professional-enterprise"],
      departmentIds: ["product"],
      reportsToId: "person-amelia-park",
    },
    {
      id: "person-sage-raman",
      name: "Sage Raman",
      title: "Director, Partner Enablement",
      avatarInitials: "SR",
      brandIds: ["blaze", "sonance"],
      channelIds: ["professional-audio", "professional-enterprise"],
      departmentIds: ["marketing", "sales"],
      reportsToId: "person-omar-hassan",
    },
  ] satisfies Person[],
};
